version: '3.6'

services:
  oauth-register:
    container_name: oauth-register
    image: oauth-register:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '0.0.0.0:7009:7009'
    restart: always
    networks:
      - make-network

networks:
  make-network:
    name: make-network
    driver: bridge