server:
  port: 7009

spring:
  mvc:
    servlet:
      path: /api/sdu
  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/make
    username: postgres
    password: senha001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: "4e2413ba332cf68d417f97523fc5c8faa72bacb9b1b2034de7326ecb2a635433fefb27e7aa1a2a9a656cb591ac050fd6112297c81282d4e6c0983d9add531ad0"


logging:
  driver:
    options:
      max-size: 128m
      max-file: 2

integration:
  api:
    validate: http://localhost:7000/api/notification
    notification: http://localhost:7001/api/temporary-code

eureka:
  client:
    enabled: false