server:
  port: 7009

spring:
  mvc:
    servlet:
      path: /api/sdu
  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/make
    username: postgres
    password: senha001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  driver:
    options:
      max-size: 128m
      max-file: 2


integration:
  api:
    validate: http://localhost:7000/api/notification
    notification: http://localhost:7001/api/temporary-code

eureka:
  client:
    service-url:
      defaultZone: https://spring-registery.bagaggio.com.br/eureka
    instance:
      hostname: oauth-register
      instance-id: ${spring.application.name}:${instanceId:${random.value}}