name: Build and Deploy OAuth Application

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: MAKEDOCKER
    environment: oauth-register-production
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    steps:
      - name: Git checkout v3
        uses: actions/checkout@v3

      - name: Use node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          architecture: 'x64'

      - name: Debug deploy date TZ
        run: echo "Running at! $(date +%Y%m%d-%H:%M:%S)"

      - name: Renomear container atual para rollback
        run: '[ -z "$(docker images -q oauth-register:latest)" ] || docker tag oauth-register:latest oauth-register:bkp-$(date +%Y%m%d-%H%M%S)'

      - name: Build da imagem
        run: docker compose build --no-cache --build-arg BUILD_DATE=$(date +%Y%m%d-%H%M%S) oauth-register

      - name: Start da aplicação
        run: docker compose up -d --force-recreate oauth-register

      - name: Mantém apenas as últimas 07 imagens de oauth-register
        run: if [ $(docker image ls --all -q oauth-register | sed -n 7,1000p | wc -l ) -ge 1 ]; then docker rmi -f $(docker image ls --all -q oauth-register | sed -n 7,1000p); fi